# Generated by Django 5.1 on 2024-08-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsForDates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogdata',
            name='id',
        ),
        migrations.AddField(
            model_name='dogdata',
            name='img',
            field=models.ImageField(default='missingImage.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='dogdata',
            name='title',
            field=models.CharField(default='Dog', max_length=50, primary_key=True, serialize=False),
        ),
    ]
