# Generated by Django 5.1 on 2024-08-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsForDates', '0002_remove_dogdata_id_dogdata_img_dogdata_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dogdata',
            name='title',
            field=models.CharField(default='Dog', max_length=50),
        ),
    ]
