# Generated by Django 5.1 on 2024-08-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsForDates', '0004_alter_dogdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
