# Generated by Django 5.1 on 2024-08-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsForDates', '0005_alter_dogdata_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Dog', max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
