# Generated by Django 5.1 on 2024-08-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogsForDates', '0006_cartdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogdata',
            old_name='img',
            new_name='image',
        ),
    ]
